### ISSUE TITLE
format of SK parameters

### ISSUE THREAD

**Issue by anshugaur** [Infant83/TBFIT#4]
Hi,
Is there a general way of converting fitted parameters to sk parameter files (slako format) used by dftb+ code? https://www.dftb.org/fileadmin/DFTB/public/misc/slakoformat.pdf
What are the units used in parameter files?
Any help or directions in this regard are greatly appreciated.

**Comment by Infant83** [comment]
Hi,

I think there should be additional parameters, for example, the repulsion parameters for the total energy calculations in the DFTB SK files.
In TBFIT there is no such parameters since we do not fit total energy.
Thus, I think there is no such general way of conversion from TBFIT to DFTB parameter files. 

The unit of TBFIT is eV.

Sincerely, 
Hyun-Jung.

___________________________________________
Hyun-Jung Kim, Ph. D. 
Peter Grünberg Institut (PGI-1) and 
Institute for Advanced Simulation (IAS-1)
Forschungszentrum Jülich, 52428 Jülich, Germany
–––––––––––––––––––––––––––––––––––––––––––
Office: Room 110, Bldg. 04.12.
Phone : +49 2461 61-1719
Publication list: google.scholar
–––––––––––––––––––––––––––––––––––––––––––
